name: size-label
on: pull_request
permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
