name: Validate YAML
on:
  push:
    paths-ignore:
    - "**.md"
    - "LICENSE"
    branches: [ main ]
  pull_request:
    paths-ignore:
    - "**.md"
    - "LICENSE"
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.2
        with:
          comment: true
          github_token: ${{ github.token }}
